<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AlohaKit" Version="1.0.100" />
    <PackageVersion Include="AutoFixture" Version="4.17.0" />
    <PackageVersion Include="AutoFixture.AutoMoq" Version="4.17.0" />
    <PackageVersion Include="AutoFixture.Xunit2" Version="4.17.0" />
    <PackageVersion Include="CommunityToolkit.Maui" Version="15.0.1" />
    <PackageVersion Include="CommunityToolkit.MVVM" Version="8.4.0" />
    <PackageVersion Include="CsvHelper" Version="33.1.0" />
    <PackageVersion Include="DataGridExtensions" Version="2.5.15" />
    <PackageVersion Include="Docnet.Core" Version="2.7.0-alpha.1" />
    <PackageVersion Include="DotNetProjects.Extended.Wpf.Toolkit" Version="5.0.124" />
    <PackageVersion Include="Emoji.Wpf" Version="0.3.4" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="11.0.0-preview.7.26381.103" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageVersion Include="Moq" Version="4.18.2" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="NLog" Version="6.0.2" />
    <PackageVersion Include="OxyPlot.Wpf" Version="2.1.0" />
    <PackageVersion Include="Plugin.Maui.Audio" Version="3.1.1" />
    <PackageVersion Include="Prism.Core" Version="9.0.537" />
    <PackageVersion Include="SimpleToolkit.Core" Version="6.0.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.15.0.120848" />
    <PackageVersion Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.1.118" />
    <PackageVersion Include="System.Linq.Async" Version="6.0.1" />
    <PackageVersion Include="UraniumUI" Version="2.11.0" />
    <PackageVersion Include="WPFChromeTabsMVVM" Version="1.4.0" />
    <PackageVersion Include="Xceed.Product.Maui.Toolkit.Full" Version="1.7.24157.1331" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
	<PackageVersion Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
	<PackageVersion Include="Microsoft.Maui.Controls.Compatibility" Version="11.0.0-preview.5.26304.4" />
	<PackageVersion Include="Microsoft.Maui.Essentials" Version="$(MauiVersion)" />
	<PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="11.0.0-preview.7.26381.103" />
  </ItemGroup>
</Project>